spring.application.name=ms-salidas
spring.config.import=optional:configserver:http://localhost:8888
# Esto obliga a la app a reintentar o fallar si el server no está
spring.cloud.config.fail-fast=true