server.port=8080

# Ruteo Manual (Sin Eureka)
spring.cloud.gateway.routes[0].id=ms-entradas
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/entradas/**

spring.cloud.gateway.routes[1].id=ms-salidas
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/salidas/**

spring.cloud.gateway.routes[2].id=ms-resumen
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/resumen/**

# Configuración de CORS para que el Frontend (React) pueda consultar
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE