server.port=8083
spring.application.name=ms-resumen

# URLs de los microservicios (puertos estáticos)
servicio.entradas.url=http://localhost:8081/api/entradas/reporte
servicio.salidas.url=http://localhost:8082/api/salidas/reporte