server.port=8888
spring.application.name=config-server

# Configuración para leer archivos locales (Perfil Native)
spring.profiles.active=native
# Ruta relativa hacia la carpeta de configuraciones que crearemos en el siguiente paso
spring.cloud.config.server.native.search-locations=file:../configurations